# based on: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
# https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix

name: MSBuild

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]
        build_architecture: [x86, x64]
        build_configuration: [Debug, Release]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      # cmake examples:
      #  - https://github.com/madler/zlib/blob/develop/.github/workflows/cmake.yml
      #  - https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml

      - name: Configure CMake
        working-directory: ${{ github.workspace }}
        run: cmake --preset ${{ matrix.build_architecture }}

      - name: Build
        working-directory: ${{ github.workspace }}
        run: cmake --build --preset ${{ matrix.build_architecture }}-${{ matrix.build_configuration }} --parallel

      - name: Test
        working-directory: ${{ github.workspace }}
        # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
        # run: ctest --build-config ${{ matrix.build_configuration }}
        run: ctest --test-dir _build_\${{ matrix.build_architecture }} --build-config ${{ matrix.build_configuration }}
